### ISSUE TITLE
Better "not implemented" errors for torchscript classes

### ISSUE THREAD

**Issue by frostedoyster** [metatensor/metatensor#737] opened 2024-09-24 06:18 UTC
Many times when I do something stupid in metatensor-torch, I get errors of this kind:
```
Traceback (most recent call last):
    energies_predicted = predictions["energy"].block() / torch.tensor([len(sys.positions) for sys in systems], device="cuda")
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
NotImplementedError: '%s' is not implemented for %s
```
Here, a block is being divided by a tensor

**Comment by Luthaf** [comment] 2024-09-24 08:51
Hmm, this is not an error that comes from metatensor ... Maybe it's from torch? Or a default Python thing?

**Comment by Luthaf** [comment] 2024-10-10 14:49
Can you share some code to reproduce the error?

**Comment by Luthaf** [comment] 2024-10-23 16:09
Closing since this can not be reproduced

**Closed by Luthaf** 2024-10-23 16:09 UTC
Labels: Torch-API, Missing reproduction
